import { LegalDocumentScreen } from '../src/components/LegalDocumentScreen';

const SECTIONS = [
  {
    title: 'Purpose',
    body: 'ReviewHelm is designed to help you build better code review habits and improve your skills over time. Its checklists, guides, and AI-powered features are educational tools meant to support — not replace — your own judgment and expertise.',
  },
  {
    title: 'No Guarantee of Quality',
    body: 'Using ReviewHelm does not guarantee that your code, or code you review, is free of bugs, security vulnerabilities, performance issues, or other defects. Checklists are curated guidelines, not exhaustive specifications.',
  },
  {
    title: 'Not a Substitute for Human Review',
    body: 'ReviewHelm is intended to complement thorough human code review, not to replace it. Always apply your own critical thinking and domain knowledge when reviewing or shipping code.',
  },
  {
    title: 'AI-Generated Content',
    body: 'AI-powered features (deep dives, comment drafting, tutoring) are generated by large language models. While helpful, AI responses may contain inaccuracies, omissions, or outdated information. Always verify AI suggestions before acting on them.',
  },
  {
    title: 'Trademarks & Third-Party Branding',
    body: 'ReviewHelm is not affiliated with, endorsed by, or officially connected to any of the companies, organizations, or projects whose technologies are covered by our checklists. All product names, logos, and brands referenced within the app (including but not limited to language names, framework names, and tool names) are the property of their respective owners and are used here solely for identification and educational purposes. The checklists, guides, and review content in ReviewHelm are independently created by ReviewHelm and do not represent official guidance from any third party.',
  },
  {
    title: 'Your Responsibility',
    body: 'You are solely responsible for the code you write, review, and approve. ReviewHelm is a learning aid — the final decision on code quality, security, and correctness is always yours and your team\'s.',
  },
];

export default function DisclaimerScreen() {
  return (
    <LegalDocumentScreen
      title="Disclaimer"
      intro="Please read this disclaimer carefully before using ReviewHelm."
      sections={SECTIONS}
      lastUpdated="March 2026"
    />
  );
}
