import type {
  Session,
  SessionScores,
  ChecklistItem,
  Severity,
} from '../data/types';
import { CONFIDENCE_LABELS } from '../data/types';
import type { ConfidenceLevel } from '../data/types';

const SEVERITY_ICON: Record<Severity, string> = {
  blocker: 'BLOCKER',
  major: 'MAJOR',
  minor: 'Minor',
  nit: 'Nit',
};

export function generateSessionMarkdown(
  session: Session,
  scores: SessionScores,
  allItems: ChecklistItem[],
  stackTitle: string,
): string {
  const lines: string[] = [];

  lines.push(`# ReviewHelm Report: ${session.title}`);
  lines.push('');
  lines.push(`**Stack:** ${stackTitle}`);
  lines.push(`**Mode:** ${session.mode}`);
  lines.push(
    `**Date:** ${session.completedAt ? new Date(session.completedAt).toLocaleDateString() : new Date(session.updatedAt).toLocaleDateString()}`,
  );
  lines.push('');

  lines.push('## Scores');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Coverage | ${scores.coverage}% |`);
  lines.push(`| Confidence | ${scores.confidence}% |`);
  lines.push(`| Total Issues | ${scores.totalIssues} |`);
  lines.push(`| Items Responded | ${scores.itemsResponded}/${scores.applicableItems} |`);
  lines.push('');

  if (scores.totalIssues > 0) {
    lines.push('### Issues by Severity');
    lines.push('');
    for (const [severity, count] of Object.entries(scores.issuesBySeverity)) {
      if (count > 0) {
        lines.push(`- **${SEVERITY_ICON[severity as Severity]}:** ${count}`);
      }
    }
    lines.push('');
  }

  // Issues found
  const issues = allItems.filter(
    (item) => session.itemResponses[item.id]?.verdict === 'needs-attention',
  );
  if (issues.length > 0) {
    lines.push('## Issues Found');
    lines.push('');
    for (const item of issues) {
      const response = session.itemResponses[item.id];
      const conf = response?.confidence as ConfidenceLevel;
      lines.push(
        `- **[${SEVERITY_ICON[item.severity]}]** ${item.text} — confidence: ${CONFIDENCE_LABELS[conf] ?? conf}`,
      );
      if (response?.notes) {
        lines.push(`  > ${response.notes}`);
      }
      if (response?.draftedComment) {
        lines.push(`  **Draft comment:** ${response.draftedComment}`);
      }
    }
    lines.push('');
  }

  // Low confidence items
  const lowConfidence = allItems.filter((item) => {
    const response = session.itemResponses[item.id];
    return (
      response &&
      response.verdict !== 'na' &&
      response.confidence <= 2
    );
  });
  if (lowConfidence.length > 0) {
    lines.push('## Low Confidence Items');
    lines.push('');
    for (const item of lowConfidence) {
      const response = session.itemResponses[item.id];
      const conf = response?.confidence as ConfidenceLevel;
      lines.push(
        `- ${item.text} — ${CONFIDENCE_LABELS[conf] ?? conf} (${item.severity})`,
      );
    }
    lines.push('');
  }

  if (session.sessionNotes.trim()) {
    lines.push('## Session Notes');
    lines.push('');
    lines.push(session.sessionNotes);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by ReviewHelm*');

  return lines.join('\n');
}
