// Lua base content - generated by Claude
module.exports = {

// GENERAL CODE QUALITY (1-5)
"lua.general-code-quality.does-the-pr-have-a-clear-description-of-what-it-does-and-why": {
  whatItMeans: "The PR description should explain the purpose of the change, the problem it solves, and any relevant context.",
  whyItMatters: "Reviewers without context waste time reverse-engineering intent from code. A clear description speeds up review and creates a searchable historical record.",
  howToVerify: "Read the PR description. Can you understand what changed and why without reading the code? Is there a link to a ticket or design doc?",
  exampleComment: "Could you add more context to the PR description? It would help to know why we are restructuring the module loading logic.",
  codeExamples: [],
  keyTakeaway: "A good PR description saves more reviewer time than it costs to write.",
  references: []
},
"lua.general-code-quality.is-the-change-scoped-appropriately": {
  whatItMeans: "Each PR should do one thing. Mixing a bug fix with a refactor makes review harder and rollbacks riskier.",
  whyItMatters: "Large, multi-concern PRs are slow to review, prone to rubber-stamping, and difficult to revert if one part causes issues.",
  howToVerify: "Check if the PR touches multiple unrelated areas. Could any part ship independently?",
  exampleComment: "This PR adds the new parser and also refactors the config module. Could we split these into two PRs?",
  codeExamples: [],
  keyTakeaway: "One concern per PR. If you need a paragraph to explain what it does, it is probably too big.",
  references: []
},
"lua.general-code-quality.are-there-any-unrelated-changes-bundled-in": {
  whatItMeans: "Drive-by fixes, formatting changes, or unrelated tweaks included alongside the main change.",
  whyItMatters: "Unrelated changes obscure the actual diff, make git blame less useful, and complicate reverts.",
  howToVerify: "Scan the file list. Are there files that do not seem related to the PR's stated purpose?",
  exampleComment: "The whitespace fixes in utils.lua look unrelated to the parser changes. Mind pulling those into a separate PR?",
  codeExamples: [],
  keyTakeaway: "Keep PRs focused. Save drive-by fixes for a dedicated cleanup PR.",
  references: []
},
"lua.general-code-quality.is-dead-code-removed-rather-than-commented-out": {
  whatItMeans: "Code that is no longer used should be deleted, not commented out. Version control preserves history.",
  whyItMatters: "Commented-out code creates confusion about whether it is temporarily disabled or a leftover. It adds noise and often never gets cleaned up.",
  howToVerify: "Search the diff for large blocks of commented-out code. Check for unused functions.",
  exampleComment: "This commented-out handler has been here since the original implementation. Since we have git history, let us remove it.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- function old_process(data)\n--   return legacy_transform(data)\n-- end\n\nfunction process(data)\n  return transform(data)\nend" },
    { label: "Good", language: "lua", code: "function process(data)\n  return transform(data)\nend" }
  ],
  keyTakeaway: "Delete dead code. Git remembers so you do not have to.",
  references: []
},
"lua.general-code-quality.are-todofixme-comments-accompanied-by-a-tracking-ticket": {
  whatItMeans: "TODO and FIXME comments should reference a ticket number so the work is tracked.",
  whyItMatters: "Untracked TODOs accumulate as tech debt that nobody owns. With a ticket, the work enters the backlog.",
  howToVerify: "Search the diff for TODO, FIXME, HACK comments. Do they include a ticket reference?",
  exampleComment: "This TODO does not have a tracking ticket. Could you file one and reference it here?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- TODO: handle pagination\nlocal results = fetch_all()" },
    { label: "Good", language: "lua", code: "-- TODO(PROJ-1234): add pagination for large result sets\nlocal results = fetch_all()" }
  ],
  keyTakeaway: "Every TODO should have an owner. A ticket number is the simplest way to assign one.",
  references: []
},

// LUA STYLE & IDIOMS (6-15)
"lua.lua-style-idioms.are-local-variables-used-instead-of-globals-wherever-possible": {
  whatItMeans: "Variables and functions should be declared with `local` unless they intentionally need global scope. Lua uses global scope by default.",
  whyItMatters: "Global variables pollute the global namespace, cause subtle bugs from name collisions, and are significantly slower than locals due to global table lookups.",
  howToVerify: "- Check for variable assignments without `local` keyword\n- Run a linter like luacheck that flags global access\n- Look for function definitions without `local`",
  exampleComment: "This function `process_data` is defined without `local`, making it a global. Could you add `local` to prevent namespace pollution?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "count = 0\nfunction increment()\n  count = count + 1\nend" },
    { label: "Good", language: "lua", code: "local count = 0\nlocal function increment()\n  count = count + 1\nend" }
  ],
  keyTakeaway: "Always use `local` unless you have a specific reason for global scope.",
  references: [{ title: "Lua Performance Tips - Local Variables", url: "https://www.lua.org/gems/sample.pdf" }]
},
"lua.lua-style-idioms.are-variable-and-function-names-descriptive-and-consistent": {
  whatItMeans: "Names should clearly convey purpose and follow a consistent convention (typically snake_case in Lua).",
  whyItMatters: "Inconsistent or cryptic naming makes code harder to read and maintain. Following community conventions helps onboard new developers.",
  howToVerify: "- Check that names describe what they hold or do\n- Verify consistent casing convention throughout the file\n- Look for single-letter names outside of loop iterators",
  exampleComment: "The variable `d` is not descriptive. Could you rename it to something like `duration_ms` or `elapsed_time`?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local d = get_data()\nlocal function proc(x, y)\n  return x + y\nend" },
    { label: "Good", language: "lua", code: "local user_data = get_data()\nlocal function calculate_total(price, tax)\n  return price + tax\nend" }
  ],
  keyTakeaway: "Use snake_case and descriptive names. Code is read far more often than it is written.",
  references: [{ title: "Lua Style Guide", url: "https://github.com/luarocks/lua-style-guide" }]
},
"lua.lua-style-idioms.are-modules-structured-using-the-return-table-pattern": {
  whatItMeans: "Lua modules should define local functions and return a table of public APIs at the end, rather than setting globals.",
  whyItMatters: "The return-table pattern is the standard module pattern in Lua. It provides clear encapsulation, avoids global pollution, and works with `require()`.",
  howToVerify: "- Check that the file ends with `return M` or similar\n- Verify functions are defined as locals and added to the module table\n- Ensure the module does not set global variables",
  exampleComment: "This module sets functions as globals instead of returning a table. Could you restructure it to use the `local M = {}; ... return M` pattern?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- mymodule.lua\nfunction greet(name)\n  print('Hello, ' .. name)\nend" },
    { label: "Good", language: "lua", code: "-- mymodule.lua\nlocal M = {}\n\nfunction M.greet(name)\n  print('Hello, ' .. name)\nend\n\nreturn M" }
  ],
  keyTakeaway: "Use the return-table pattern for modules: `local M = {}; ... return M`.",
  references: [{ title: "Programming in Lua - Modules", url: "https://www.lua.org/pil/15.html" }]
},
"lua.lua-style-idioms.is-local-keyword-used-for-loop-variables-and-temporary-values": {
  whatItMeans: "Loop variables in `for` loops are automatically local, but temporary variables inside loops should be explicitly declared `local`.",
  whyItMatters: "Forgetting `local` inside a loop body creates globals that persist after the loop and can cause subtle bugs across iterations or modules.",
  howToVerify: "- Check variable assignments inside loop bodies for missing `local`\n- Run luacheck to detect accidental globals",
  exampleComment: "The variable `result` inside the for loop is missing `local`. This creates a global that leaks outside the loop.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "for i = 1, #items do\n  result = process(items[i])  -- global!\n  table.insert(output, result)\nend" },
    { label: "Good", language: "lua", code: "for i = 1, #items do\n  local result = process(items[i])\n  table.insert(output, result)\nend" }
  ],
  keyTakeaway: "Always declare temporary variables inside loops as `local`.",
  references: []
},
"lua.lua-style-idioms.are-metatables-used-correctly-and-not-overcomplicating-simple-structures": {
  whatItMeans: "Metatables should be used when you need operator overloading, inheritance, or custom behavior. Simple data structures do not need them.",
  whyItMatters: "Overusing metatables makes code harder to understand and debug. They add indirection that can surprise other developers reading the code.",
  howToVerify: "- Check if metatable usage is justified by the use case\n- Verify __index chains are not overly deep\n- Ensure metatables are not used for simple key-value storage",
  exampleComment: "This data table uses a metatable with __index just to provide default values. A simpler approach would be to set defaults inline.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local defaults = { timeout = 30, retries = 3 }\nlocal config = setmetatable({}, { __index = defaults })" },
    { label: "Good", language: "lua", code: "local config = {\n  timeout = opts.timeout or 30,\n  retries = opts.retries or 3,\n}" }
  ],
  keyTakeaway: "Use metatables for OOP and operator overloading, not for simple defaults or data.",
  references: [{ title: "Programming in Lua - Metatables", url: "https://www.lua.org/pil/13.html" }]
},
"lua.lua-style-idioms.are-string-concatenation-operations-using-tableconcat-for-performance": {
  whatItMeans: "Building strings in loops should use `table.concat` instead of the `..` operator to avoid creating intermediate string objects.",
  whyItMatters: "Lua strings are immutable. Each `..` operation creates a new string, leading to O(n^2) behavior when concatenating in loops.",
  howToVerify: "- Look for `..` inside loops that build up strings\n- Check if `table.concat` is used for joining multiple parts",
  exampleComment: "This loop concatenates strings with `..` on each iteration, which is O(n^2). Could you collect parts in a table and use `table.concat` at the end?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local result = ''\nfor i = 1, #lines do\n  result = result .. lines[i] .. '\\n'\nend" },
    { label: "Good", language: "lua", code: "local parts = {}\nfor i = 1, #lines do\n  parts[#parts + 1] = lines[i]\nend\nlocal result = table.concat(parts, '\\n')" }
  ],
  keyTakeaway: "Use `table.concat` for string building in loops. It is O(n) instead of O(n^2).",
  references: [{ title: "Lua Performance Tips", url: "https://www.lua.org/gems/sample.pdf" }]
},
"lua.lua-style-idioms.are-numeric-for-loops-used-with-correct-step-values": {
  whatItMeans: "Numeric `for` loops should have correct start, stop, and step values. Common mistakes include off-by-one errors and missing step for reverse iteration.",
  whyItMatters: "Incorrect loop bounds cause skipped elements or infinite loops. Lua's 1-based indexing makes off-by-one errors especially common.",
  howToVerify: "- Verify start and end values account for 1-based indexing\n- Check reverse loops include `-1` step\n- Ensure step value matches the iteration direction",
  exampleComment: "This reverse loop is missing the `-1` step parameter. Without it, the loop body will never execute.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- Missing step, never executes\nfor i = #items, 1 do\n  process(items[i])\nend" },
    { label: "Good", language: "lua", code: "for i = #items, 1, -1 do\n  process(items[i])\nend" }
  ],
  keyTakeaway: "Always include the step parameter for reverse loops: `for i = n, 1, -1`.",
  references: [{ title: "Lua Reference - for", url: "https://www.lua.org/manual/5.4/manual.html#3.3.5" }]
},
"lua.lua-style-idioms.is-ipairs-used-for-arrays-and-pairs-for-hash-tables": {
  whatItMeans: "Use `ipairs` for sequential integer-keyed arrays (stops at first nil) and `pairs` for tables with arbitrary keys.",
  whyItMatters: "Using `pairs` on arrays does not guarantee order. Using `ipairs` on hash tables skips non-integer keys. Using the wrong iterator leads to bugs.",
  howToVerify: "- Check that `ipairs` is used for array-style tables\n- Verify `pairs` is used for dictionary-style tables\n- Look for cases where the wrong iterator could miss or reorder elements",
  exampleComment: "This uses `pairs` to iterate over what looks like a sequential array. `ipairs` would guarantee order and be more idiomatic.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local names = {'Alice', 'Bob', 'Charlie'}\nfor k, v in pairs(names) do  -- unordered!\n  print(k, v)\nend" },
    { label: "Good", language: "lua", code: "local names = {'Alice', 'Bob', 'Charlie'}\nfor i, name in ipairs(names) do\n  print(i, name)\nend" }
  ],
  keyTakeaway: "Use `ipairs` for arrays (ordered), `pairs` for hash tables (unordered).",
  references: [{ title: "Lua Reference - ipairs", url: "https://www.lua.org/manual/5.4/manual.html#pdf-ipairs" }]
},
"lua.lua-style-idioms.are-varargs-handled-correctly-with-select-or-table-packing": {
  whatItMeans: "Variadic arguments (`...`) should be handled with `select('#', ...)` for count or `table.pack(...)` to preserve nil values in the argument list.",
  whyItMatters: "Using `#` on `{...}` stops at the first nil, losing trailing arguments. `select('#', ...)` and `table.pack` correctly handle nil values.",
  howToVerify: "- Check for `#{...}` usage which may lose trailing nils\n- Verify `select('#', ...)` or `table.pack(...)` is used for count\n- Look for direct `...` usage that might lose arguments",
  exampleComment: "Using `#{...}` to count varargs will be wrong if any argument is nil. Use `select('#', ...)` instead.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local function log(...)\n  local args = {...}\n  local n = #args  -- wrong if args contain nil\n  for i = 1, n do print(args[i]) end\nend" },
    { label: "Good", language: "lua", code: "local function log(...)\n  local n = select('#', ...)\n  for i = 1, n do\n    print(select(i, ...))\n  end\nend" }
  ],
  keyTakeaway: "Use `select('#', ...)` for vararg count. `#{...}` breaks with nil arguments.",
  references: [{ title: "Lua Reference - select", url: "https://www.lua.org/manual/5.4/manual.html#pdf-select" }]
},
"lua.lua-style-idioms.are-nil-comparisons-explicit-rather-than-relying-on-truthiness": {
  whatItMeans: "When checking if a value is nil, use explicit `== nil` or `~= nil` comparisons rather than relying on Lua truthiness, especially when `false` is a valid value.",
  whyItMatters: "In Lua, both `nil` and `false` are falsy. Code that checks `if not value` when `false` is a valid value will incorrectly treat `false` as missing.",
  howToVerify: "- Look for `if value then` or `if not value then` where `false` could be a valid value\n- Check boolean config values that could legitimately be `false`",
  exampleComment: "The check `if not config.debug then` will be true when debug is `false` (disabled) AND when it is `nil` (unset). Did you mean `if config.debug == nil`?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- Fails when enabled is explicitly false\nif not config.enabled then\n  config.enabled = true  -- overwrites false!\nend" },
    { label: "Good", language: "lua", code: "if config.enabled == nil then\n  config.enabled = true  -- only sets default\nend" }
  ],
  keyTakeaway: "Use explicit nil checks when `false` is a valid value in your domain.",
  references: []
},

// TABLES & DATA STRUCTURES (16-21)
"lua.tables-data-structures.are-tables-used-as-arrays-not-mixed-with-hash-keys": {
  whatItMeans: "Tables used as arrays should only have sequential integer keys starting from 1. Mixing integer and string keys creates ambiguous behavior.",
  whyItMatters: "Mixed tables break `#` operator, `ipairs`, and `table.sort`. The semantics become unpredictable and performance suffers.",
  howToVerify: "- Check for tables that mix `[1]='a'` with `name='b'` style keys\n- Verify array tables only use sequential integers",
  exampleComment: "This table mixes array entries with string keys. Consider separating the array data from the metadata into two tables.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local items = {'apple', 'banana', name='fruit_list', count=2}" },
    { label: "Good", language: "lua", code: "local items = {'apple', 'banana'}\nlocal meta = {name = 'fruit_list', count = #items}" }
  ],
  keyTakeaway: "Keep array tables and hash tables separate. Mixing them causes subtle bugs.",
  references: []
},
"lua.tables-data-structures.is-operator-used-correctly-only-reliable-for-sequence-tables": {
  whatItMeans: "The `#` length operator is only reliable for sequence tables (contiguous integer keys from 1 to n). It is undefined for tables with holes.",
  whyItMatters: "Using `#` on a table with gaps returns an unpredictable value. This causes off-by-one errors and missed elements.",
  howToVerify: "- Check if `#` is used on tables that might have nil holes\n- Verify the table is a proper sequence before using `#`",
  exampleComment: "This table may have nil gaps after deletion. Using `#` on it is unreliable. Consider tracking the count separately or using `table.move`.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local t = {1, 2, nil, 4}\nprint(#t)  -- undefined! could be 2 or 4" },
    { label: "Good", language: "lua", code: "local t = {1, 2, 4}  -- no gaps\nprint(#t)  -- reliably 3" }
  ],
  keyTakeaway: "Only use `#` on proper sequences. For sparse tables, track length manually.",
  references: [{ title: "Lua Reference - Length Operator", url: "https://www.lua.org/manual/5.4/manual.html#3.4.7" }]
},
"lua.tables-data-structures.are-table-keys-consistent-types-dont-mix-string-and-integer-keys": {
  whatItMeans: "Table keys should be consistently typed. Mixing string keys like `'1'` with integer keys like `1` creates separate entries for the same logical key.",
  whyItMatters: "`t[1]` and `t['1']` are different keys in Lua. Mixing them leads to duplicate data and lookup failures.",
  howToVerify: "- Check for tables accessed with both number and string versions of keys\n- Verify IDs used as keys are consistently typed",
  exampleComment: "This table uses `t[id]` where `id` is sometimes a number and sometimes a string. Please ensure consistent key types.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local cache = {}\ncache[1] = 'first'\ncache['1'] = 'also first'  -- different key!\nprint(cache[1], cache['1'])  -- 'first', 'also first'" },
    { label: "Good", language: "lua", code: "local cache = {}\nlocal key = tostring(id)  -- always string\ncache[key] = value" }
  ],
  keyTakeaway: "Be consistent with key types. `t[1]` and `t['1']` are different entries.",
  references: []
},
"lua.tables-data-structures.are-object-oriented-patterns-using-metatables-consistent": {
  whatItMeans: "If using OOP in Lua via metatables, the pattern should be consistent: same constructor style, same method calling convention (`:` vs `.`).",
  whyItMatters: "Inconsistent OOP patterns confuse developers. Mixing `:` and `.` for method calls or using different constructor patterns makes the codebase harder to navigate.",
  howToVerify: "- Check that all classes use the same constructor pattern\n- Verify `:` is used consistently for method calls\n- Ensure `self` is passed correctly",
  exampleComment: "Some classes use `Class:new()` and others use `Class.create()`. Could we standardize on one pattern?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- Inconsistent: uses . instead of :\nfunction Dog.speak(self)\n  print(self.name .. ' barks')\nend\ndog.speak(dog)  -- manual self" },
    { label: "Good", language: "lua", code: "function Dog:speak()\n  print(self.name .. ' barks')\nend\ndog:speak()  -- auto self" }
  ],
  keyTakeaway: "Pick one OOP pattern and use it consistently. The `:` syntax is the Lua convention.",
  references: [{ title: "Programming in Lua - OOP", url: "https://www.lua.org/pil/16.html" }]
},
"lua.tables-data-structures.are-table-constructors-used-for-initialization-instead-of-sequential-assignment": {
  whatItMeans: "Tables should be initialized with constructors `{}` rather than creating an empty table and assigning fields one by one.",
  whyItMatters: "Table constructors are more readable, allocate memory in one shot, and clearly show the structure of the data at the point of creation.",
  howToVerify: "- Look for empty table creation followed by multiple field assignments\n- Check if the initialization could be done in a single constructor",
  exampleComment: "These sequential assignments could be combined into a single table constructor for better readability.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local config = {}\nconfig.host = 'localhost'\nconfig.port = 8080\nconfig.debug = false" },
    { label: "Good", language: "lua", code: "local config = {\n  host = 'localhost',\n  port = 8080,\n  debug = false,\n}" }
  ],
  keyTakeaway: "Use table constructors for initialization. They are clearer and more efficient.",
  references: []
},
"lua.tables-data-structures.are-weak-tables-used-where-garbage-collection-of-values-is-needed": {
  whatItMeans: "Tables that serve as caches or registries should use weak references (`__mode = 'v'` or `__mode = 'k'`) so entries can be garbage collected.",
  whyItMatters: "Without weak references, cached objects are never collected, causing memory leaks. Weak tables let the GC reclaim entries when nothing else references them.",
  howToVerify: "- Check cache/registry tables for weak mode metatable\n- Look for growing tables that should shrink when objects are no longer used",
  exampleComment: "This object cache will grow indefinitely. Since it is a cache, consider using `setmetatable(cache, {__mode = 'v'})` so entries can be garbage collected.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local cache = {}  -- strong refs, never collected\nfunction get_widget(id)\n  if not cache[id] then\n    cache[id] = create_widget(id)\n  end\n  return cache[id]\nend" },
    { label: "Good", language: "lua", code: "local cache = setmetatable({}, { __mode = 'v' })\nfunction get_widget(id)\n  if not cache[id] then\n    cache[id] = create_widget(id)\n  end\n  return cache[id]\nend" }
  ],
  keyTakeaway: "Use weak tables for caches so the garbage collector can reclaim unused entries.",
  references: [{ title: "Programming in Lua - Weak Tables", url: "https://www.lua.org/pil/17.html" }]
},

// ERROR HANDLING (22-26)
"lua.error-handling.are-pcall-and-xpcall-used-for-protected-calls": {
  whatItMeans: "Operations that can fail should be wrapped in `pcall` or `xpcall` to catch errors without crashing the program.",
  whyItMatters: "Unprotected calls that error will terminate the program or propagate up to the nearest pcall. Critical code paths need explicit error protection.",
  howToVerify: "- Check that I/O, network, and parsing operations are wrapped in pcall\n- Verify xpcall is used when a stack trace is needed\n- Ensure the error return is checked",
  exampleComment: "This file read operation is not protected. If the file does not exist, the program will crash. Could you wrap it in `pcall`?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local data = json.decode(raw_input)  -- crashes on invalid JSON" },
    { label: "Good", language: "lua", code: "local ok, data = pcall(json.decode, raw_input)\nif not ok then\n  log.error('Invalid JSON: ' .. tostring(data))\n  return nil, data\nend" }
  ],
  keyTakeaway: "Use pcall/xpcall for any operation that can fail. Check the return values.",
  references: [{ title: "Lua Reference - pcall", url: "https://www.lua.org/manual/5.4/manual.html#pdf-pcall" }]
},
"lua.error-handling.are-error-messages-descriptive-with-relevant-context": {
  whatItMeans: "Error messages should include what went wrong, where, and with what data. Generic messages like 'error occurred' are not helpful.",
  whyItMatters: "Descriptive error messages dramatically reduce debugging time. They tell you exactly what failed without needing to reproduce the issue.",
  howToVerify: "- Check error() calls for descriptive messages\n- Verify context (function name, input values) is included\n- Look for generic messages that should be specific",
  exampleComment: "The error message 'invalid input' does not say what was invalid. Could you include the actual value and what was expected?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "error('invalid input')" },
    { label: "Good", language: "lua", code: "error(string.format(\n  'parse_config: expected string for host, got %s (%s)',\n  type(host), tostring(host)\n))" }
  ],
  keyTakeaway: "Include what, where, and why in error messages. Your future self is the audience.",
  references: []
},
"lua.error-handling.are-error-calls-using-level-parameter-correctly": {
  whatItMeans: "The `error()` function accepts a level parameter that controls where the error appears to originate. Level 1 (default) is the caller, level 2 is the caller's caller.",
  whyItMatters: "Using the right error level makes debugging easier by pointing to the actual call site rather than the validation function that detected the error.",
  howToVerify: "- Check error() calls in validation/assertion functions for appropriate level\n- Verify level 2 is used when reporting errors on behalf of callers",
  exampleComment: "This validation function uses `error(msg)` (level 1), which points to the validation function itself. Using `error(msg, 2)` would point to the caller, which is more helpful.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local function check_type(val, expected)\n  if type(val) ~= expected then\n    error('wrong type')  -- points here, not caller\n  end\nend" },
    { label: "Good", language: "lua", code: "local function check_type(val, expected)\n  if type(val) ~= expected then\n    error('expected ' .. expected .. ', got ' .. type(val), 2)\n  end\nend" }
  ],
  keyTakeaway: "Use error level 2 in validation functions so the error points to the caller.",
  references: [{ title: "Lua Reference - error", url: "https://www.lua.org/manual/5.4/manual.html#pdf-error" }]
},
"lua.error-handling.is-the-ok-err-pattern-used-consistently-for-error-propagation": {
  whatItMeans: "Functions that can fail should return `value, nil` on success and `nil, error_message` on failure, following Lua's conventional error pattern.",
  whyItMatters: "Consistent error return patterns make error handling predictable. Callers know to check the first return value and handle the error in the second.",
  howToVerify: "- Check that fallible functions return nil, err on failure\n- Verify callers check both return values\n- Look for functions that sometimes return nil and sometimes error()",
  exampleComment: "This function calls `error()` on some failures and returns `nil, msg` on others. Could you standardize on the `nil, err` pattern?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "function read_config(path)\n  local f = io.open(path)\n  if not f then error('cannot open') end  -- throws!\n  return parse(f:read('*a'))\nend" },
    { label: "Good", language: "lua", code: "function read_config(path)\n  local f, err = io.open(path)\n  if not f then return nil, 'cannot open: ' .. err end\n  local data, parse_err = parse(f:read('*a'))\n  f:close()\n  return data, parse_err\nend" }
  ],
  keyTakeaway: "Use `nil, err` returns consistently. Reserve `error()` for programming errors.",
  references: []
},
"lua.error-handling.are-assertion-failures-assert-appropriate-for-the-context": {
  whatItMeans: "`assert()` should be used for conditions that indicate programming errors, not for expected runtime failures like missing files or bad user input.",
  whyItMatters: "assert terminates the program on failure. Using it for expected failures (network errors, invalid input) crashes the program when it should recover gracefully.",
  howToVerify: "- Check that assert is used for invariants and preconditions, not runtime errors\n- Verify assert messages are descriptive\n- Look for assert on I/O or network operations",
  exampleComment: "Using `assert(io.open(path))` will crash the program if the file is missing. This is a recoverable error that should use an if-check instead.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- Crashes if file doesn't exist\nlocal f = assert(io.open(user_path))" },
    { label: "Good", language: "lua", code: "local f, err = io.open(user_path)\nif not f then\n  return nil, 'cannot open: ' .. err\nend" }
  ],
  keyTakeaway: "Use assert for invariants, not for expected runtime failures.",
  references: []
},

// PERFORMANCE (27-32)
"lua.performance.are-hot-path-locals-cached-from-global-lookups-eg-local-mathsin-mathsin": {
  whatItMeans: "Frequently accessed global functions (like `math.sin`, `string.format`, `table.insert`) should be cached in local variables at the top of the file.",
  whyItMatters: "Global lookups go through the global table on every call. Local access is significantly faster and can make a measurable difference in hot loops.",
  howToVerify: "- Check for repeated global lookups in tight loops\n- Look for missing local caching of stdlib functions used frequently",
  exampleComment: "This inner loop calls `math.sqrt` on every iteration. Caching it as `local sqrt = math.sqrt` at the top of the file would improve performance.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "for i = 1, 1000000 do\n  result[i] = math.sqrt(data[i])  -- global lookup each time\nend" },
    { label: "Good", language: "lua", code: "local sqrt = math.sqrt\nfor i = 1, 1000000 do\n  result[i] = sqrt(data[i])  -- local access\nend" }
  ],
  keyTakeaway: "Cache global functions as locals: `local insert = table.insert`. It matters in hot paths.",
  references: [{ title: "Lua Performance Tips", url: "https://www.lua.org/gems/sample.pdf" }]
},
"lua.performance.are-tables-pre-allocated-when-size-is-known": {
  whatItMeans: "When the size of a table is known in advance, use `table.create` (LuaJIT) or pre-size hints to avoid repeated reallocations.",
  whyItMatters: "Tables grow by doubling when full. Pre-allocating avoids multiple resize operations and reduces memory fragmentation.",
  howToVerify: "- Look for tables built in loops where the final size is known\n- Check for LuaJIT's table.new or table.create usage where applicable",
  exampleComment: "We know there will be exactly `n` items. Pre-allocating the table would avoid resize overhead.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local results = {}\nfor i = 1, n do\n  results[#results + 1] = compute(i)  -- grows incrementally\nend" },
    { label: "Good", language: "lua", code: "local results = {}\n-- In LuaJIT: local results = require('table.new')(n, 0)\nfor i = 1, n do\n  results[i] = compute(i)  -- direct index, no # lookup\nend" }
  ],
  keyTakeaway: "Pre-allocate tables when size is known. Use direct index assignment instead of `#t + 1`.",
  references: []
},
"lua.performance.are-string-patterns-used-efficiently-avoiding-backtracking": {
  whatItMeans: "Lua string patterns should avoid excessive backtracking. Patterns with nested quantifiers or overly broad matches can be slow.",
  whyItMatters: "Inefficient patterns can cause exponential time complexity on certain inputs, creating performance bottlenecks or even hangs.",
  howToVerify: "- Check for patterns with nested quantifiers like `(.-)(.-)` \n- Look for overly broad patterns that could be more specific\n- Consider using `string.find` with plain flag for literal matching",
  exampleComment: "This pattern `(.-)(.*)` has potential for excessive backtracking. Could you make the character classes more specific?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- Overly broad, potential backtracking\nlocal a, b = line:match('(.-)%s(.*)')" },
    { label: "Good", language: "lua", code: "-- More specific, no backtracking\nlocal a, b = line:match('(%S+)%s+(.*)')" }
  ],
  keyTakeaway: "Use specific character classes in patterns. Avoid nested quantifiers that cause backtracking.",
  references: [{ title: "Lua Reference - Patterns", url: "https://www.lua.org/manual/5.4/manual.html#6.4.1" }]
},
"lua.performance.are-closures-not-created-unnecessarily-in-loops": {
  whatItMeans: "Creating closures (anonymous functions) inside tight loops allocates a new function object on every iteration, which pressures the garbage collector.",
  whyItMatters: "Each closure allocation triggers GC work. In hot loops, this can cause noticeable pauses and slowdowns.",
  howToVerify: "- Look for `function()` definitions inside for/while loops\n- Check if the closure could be moved outside the loop\n- Verify that closures inside loops actually need per-iteration state",
  exampleComment: "This callback function is created on every iteration but does not capture any loop-specific state. Could you define it once outside the loop?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "for i = 1, #items do\n  register(items[i], function(event)\n    log(event)  -- no loop state captured\n  end)\nend" },
    { label: "Good", language: "lua", code: "local function on_event(event)\n  log(event)\nend\nfor i = 1, #items do\n  register(items[i], on_event)\nend" }
  ],
  keyTakeaway: "Move closures out of loops when they do not capture per-iteration state.",
  references: []
},
"lua.performance.is-tail-call-optimization-leveraged-where-appropriate": {
  whatItMeans: "Lua supports proper tail calls. Functions that end with `return func(args)` do not grow the stack, enabling deep recursion without overflow.",
  whyItMatters: "Tail call optimization prevents stack overflow in recursive algorithms. Without it, deep recursion crashes the program.",
  howToVerify: "- Check recursive functions for proper tail call form\n- Verify the return statement directly returns the function call with no extra operations\n- Look for `return func(x) + 1` which is NOT a tail call",
  exampleComment: "This recursive function does `return 1 + traverse(next)`. The addition prevents tail call optimization. Could you restructure to use an accumulator?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local function sum(n)\n  if n <= 0 then return 0 end\n  return n + sum(n - 1)  -- not a tail call\nend" },
    { label: "Good", language: "lua", code: "local function sum(n, acc)\n  acc = acc or 0\n  if n <= 0 then return acc end\n  return sum(n - 1, acc + n)  -- proper tail call\nend" }
  ],
  keyTakeaway: "Use tail calls for deep recursion: `return func(args)` with no operations on the result.",
  references: [{ title: "Programming in Lua - Proper Tail Calls", url: "https://www.lua.org/pil/6.3.html" }]
},
"lua.performance.are-luajit-specific-optimizations-considered-ffi-tracing": {
  whatItMeans: "When targeting LuaJIT, consider its FFI for calling C functions, and be aware of patterns that break JIT traces (like `pairs`, `pcall` in hot loops).",
  whyItMatters: "LuaJIT's FFI is orders of magnitude faster than the C API for calling C code. Understanding trace-breaking patterns helps write code that JIT-compiles efficiently.",
  howToVerify: "- Check if LuaJIT FFI could replace C API bindings\n- Look for trace-breaking patterns in hot loops (pcall, pairs, unstructured exits)\n- Verify numeric code uses proper types for JIT optimization",
  exampleComment: "This hot loop uses `pairs` which prevents JIT compilation. Could you switch to a numeric for loop with `ipairs` or direct indexing?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- pairs breaks JIT traces\nfor k, v in pairs(data) do\n  total = total + v.score\nend" },
    { label: "Good", language: "lua", code: "-- numeric for compiles well\nfor i = 1, #data do\n  total = total + data[i].score\nend" }
  ],
  keyTakeaway: "For LuaJIT: use numeric loops, FFI for C calls, and avoid trace-breaking patterns in hot code.",
  references: [{ title: "LuaJIT Performance", url: "https://luajit.org/performance.html" }]
},

// C INTEGRATION & FFI (33-36)
"lua.c-integration-ffi.are-c-api-calls-using-proper-stack-management-pushpop-balance": {
  whatItMeans: "When using the Lua C API, every value pushed onto the stack must be accounted for. Stack overflow or underflow causes crashes.",
  whyItMatters: "Unbalanced stack operations are the #1 source of C API bugs. They cause silent corruption, crashes, and security vulnerabilities.",
  howToVerify: "- Count push/pop operations in each C function\n- Check that `lua_gettop` is used to verify stack state\n- Look for missing pops after lua_pcall or lua_getfield",
  exampleComment: "This C function pushes 3 values but only pops 1. The stack will grow on each call. Please balance the push/pop operations.",
  codeExamples: [
    { label: "Bad", language: "c", code: "lua_getfield(L, -1, \"name\");\nlua_getfield(L, -2, \"age\");\n// forgot to pop unused values\nreturn 0;" },
    { label: "Good", language: "c", code: "lua_getfield(L, -1, \"name\");\nconst char *name = lua_tostring(L, -1);\nlua_pop(L, 1);  // balanced\nreturn 0;" }
  ],
  keyTakeaway: "Balance every push with a pop. Use lua_gettop to verify stack state in debug builds.",
  references: [{ title: "Lua C API Reference", url: "https://www.lua.org/manual/5.4/manual.html#4" }]
},
"lua.c-integration-ffi.are-userdata-types-validated-before-use": {
  whatItMeans: "Userdata passed to C functions should be validated with `luaL_checkudata` to ensure they are the expected type before casting.",
  whyItMatters: "Casting unvalidated userdata to a C struct pointer causes undefined behavior. An attacker could pass wrong userdata to crash or exploit the program.",
  howToVerify: "- Check that luaL_checkudata is used instead of lua_touserdata\n- Verify the metatable name matches the expected type\n- Look for raw pointer casts without type validation",
  exampleComment: "This uses `lua_touserdata` without type checking. If someone passes the wrong userdata type, it will crash. Please use `luaL_checkudata` with the type metatable.",
  codeExamples: [
    { label: "Bad", language: "c", code: "MyStruct *s = (MyStruct *)lua_touserdata(L, 1);\n// No type check - any userdata accepted!" },
    { label: "Good", language: "c", code: "MyStruct *s = (MyStruct *)luaL_checkudata(L, 1, \"MyStruct\");\n// Validates metatable matches" }
  ],
  keyTakeaway: "Always use luaL_checkudata to validate userdata types before casting.",
  references: [{ title: "Lua Auxiliary Library - checkudata", url: "https://www.lua.org/manual/5.4/manual.html#luaL_checkudata" }]
},
"lua.c-integration-ffi.is-memory-management-correct-for-c-allocated-resources": {
  whatItMeans: "C resources (file handles, sockets, memory) allocated for Lua userdata must be freed in the `__gc` metamethod to prevent leaks.",
  whyItMatters: "Without proper __gc metamethods, C resources leak when Lua garbage collects the userdata. This causes file descriptor exhaustion and memory leaks.",
  howToVerify: "- Check that userdata with C resources has a __gc metamethod\n- Verify the __gc handler frees all associated resources\n- Look for double-free guards in the __gc handler",
  exampleComment: "This userdata allocates a C socket but has no __gc metamethod. When Lua garbage collects it, the socket will leak.",
  codeExamples: [
    { label: "Bad", language: "c", code: "// No __gc - resource leaks on GC\nConn *c = lua_newuserdata(L, sizeof(Conn));\nc->fd = open_connection(host, port);" },
    { label: "Good", language: "c", code: "Conn *c = lua_newuserdata(L, sizeof(Conn));\nc->fd = open_connection(host, port);\nluaL_setmetatable(L, \"Connection\");\n// metatable has __gc = conn_gc which calls close(c->fd)" }
  ],
  keyTakeaway: "Always implement __gc for userdata that owns C resources.",
  references: []
},
"lua.c-integration-ffi.are-luajit-ffi-declarations-matching-c-headers-exactly": {
  whatItMeans: "LuaJIT FFI `ffi.cdef` declarations must exactly match the C header definitions. Mismatched struct layouts or function signatures cause crashes.",
  whyItMatters: "FFI calls are raw pointer operations. A mismatched declaration (wrong struct size, wrong calling convention) silently corrupts memory or crashes.",
  howToVerify: "- Compare ffi.cdef declarations against the actual C headers\n- Check struct field order and types match exactly\n- Verify function signatures include correct return types and parameters",
  exampleComment: "The FFI declaration has `int` for the size field but the C header uses `size_t`. On 64-bit systems, this will read the wrong number of bytes.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "ffi.cdef[[\n  typedef struct { int size; char *data; } Buffer;\n  // C header actually has: size_t size;\n]]" },
    { label: "Good", language: "lua", code: "ffi.cdef[[\n  typedef struct { size_t size; char *data; } Buffer;\n  // Matches C header exactly\n]]" }
  ],
  keyTakeaway: "FFI declarations must match C headers byte-for-byte. Verify against the actual header files.",
  references: [{ title: "LuaJIT FFI Semantics", url: "https://luajit.org/ext_ffi_semantics.html" }]
},

// TESTING & SECURITY (37-42)
"lua.testing-security.are-there-unit-tests-for-new-logic-busted-luaunit": {
  whatItMeans: "New functions and modules should have corresponding unit tests using a Lua testing framework like busted or luaunit.",
  whyItMatters: "Tests catch regressions, document expected behavior, and give confidence to refactor. Without them, changes are risky.",
  howToVerify: "- Check for new or updated test files corresponding to changed code\n- Verify tests cover the happy path and key edge cases\n- Ensure tests are runnable and passing",
  exampleComment: "This new parser module has no tests. Could you add tests for valid input, invalid input, and edge cases?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- No tests for the new parser module" },
    { label: "Good", language: "lua", code: "describe('parser', function()\n  it('parses valid input', function()\n    assert.same({1, 2, 3}, parser.parse('1,2,3'))\n  end)\n  it('returns nil on empty input', function()\n    assert.is_nil(parser.parse(''))\n  end)\nend)" }
  ],
  keyTakeaway: "Write tests for new logic. They are the safety net that makes future changes possible.",
  references: [{ title: "Busted Testing Framework", url: "https://lunarmodules.github.io/busted/" }]
},
"lua.testing-security.are-test-cases-covering-edge-cases-nil-empty-tables-boundary-values": {
  whatItMeans: "Tests should cover edge cases: nil values, empty tables, empty strings, boundary values, and unexpected types.",
  whyItMatters: "Edge cases are where most bugs hide. Testing only the happy path misses the conditions that cause production failures.",
  howToVerify: "- Check tests for nil, empty, zero, and boundary inputs\n- Look for tests of error paths and invalid inputs\n- Verify type misuse is tested",
  exampleComment: "The tests only cover valid inputs. Could you add cases for nil, empty table, and tables with nil holes?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "it('calculates sum', function()\n  assert.equal(6, sum({1, 2, 3}))\nend)" },
    { label: "Good", language: "lua", code: "it('calculates sum', function()\n  assert.equal(6, sum({1, 2, 3}))\nend)\nit('returns 0 for empty table', function()\n  assert.equal(0, sum({}))\nend)\nit('handles nil input', function()\n  assert.equal(0, sum(nil))\nend)" }
  ],
  keyTakeaway: "Test nil, empty, zero, and boundary values. That is where bugs live.",
  references: []
},
"lua.testing-security.is-user-input-from-external-sources-validated": {
  whatItMeans: "Data from external sources (network, files, user input) must be validated before use. Never trust external data.",
  whyItMatters: "Unvalidated input leads to crashes, injection attacks, and undefined behavior. External data can contain anything.",
  howToVerify: "- Check that external data is type-checked and range-validated\n- Look for direct use of network/file data without validation\n- Verify error handling for invalid input",
  exampleComment: "This network handler uses the incoming data directly without validating the type or range. Could you add input validation?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local function handle_request(data)\n  db.query(data.table_name, data.id)  -- unsanitized!\nend" },
    { label: "Good", language: "lua", code: "local ALLOWED_TABLES = {users=true, orders=true}\nlocal function handle_request(data)\n  if not ALLOWED_TABLES[data.table_name] then\n    return nil, 'invalid table'\n  end\n  if type(data.id) ~= 'number' then\n    return nil, 'invalid id'\n  end\n  db.query(data.table_name, data.id)\nend" }
  ],
  keyTakeaway: "Validate all external input. Trust nothing from outside your program boundary.",
  references: []
},
"lua.testing-security.is-loadstringload-avoided-with-untrusted-input": {
  whatItMeans: "`loadstring`/`load` compiles and potentially executes arbitrary Lua code. Using it with untrusted input is a code injection vulnerability.",
  whyItMatters: "An attacker who controls the input to `loadstring` can execute arbitrary code, read files, make network calls, or crash the system.",
  howToVerify: "- Search for loadstring, load, dofile, dostring calls\n- Check if the input could come from an untrusted source\n- Verify sandboxing is in place if dynamic code execution is required",
  exampleComment: "This uses `loadstring(user_expression)` which allows arbitrary code execution. Could you use a safe expression evaluator or whitelist approach instead?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- Code injection vulnerability!\nlocal fn = loadstring('return ' .. user_input)\nlocal result = fn()" },
    { label: "Good", language: "lua", code: "-- Safe: parse the expression manually\nlocal result = safe_eval(user_input, allowed_ops)" }
  ],
  keyTakeaway: "Never use loadstring/load with untrusted input. It is remote code execution.",
  references: []
},
"lua.testing-security.are-sandboxing-techniques-used-for-running-untrusted-scripts": {
  whatItMeans: "If untrusted Lua code must be executed, it should run in a sandbox with restricted access to dangerous functions (io, os, debug, loadstring).",
  whyItMatters: "Without sandboxing, untrusted scripts can read/write files, execute commands, access the network, and crash the host program.",
  howToVerify: "- Check that untrusted code runs with a restricted environment\n- Verify dangerous modules (io, os, debug) are removed from the sandbox\n- Look for setfenv or _ENV-based sandboxing",
  exampleComment: "This plugin system runs user scripts with full access to `io` and `os`. Could you create a sandbox environment that only exposes safe functions?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- Full access to everything\nlocal fn = load(user_code)\nfn()  -- can call os.execute, io.open, etc." },
    { label: "Good", language: "lua", code: "local sandbox = {\n  print = print, pairs = pairs, ipairs = ipairs,\n  type = type, tostring = tostring, tonumber = tonumber,\n  math = math, string = string, table = table,\n}\nlocal fn = load(user_code, 'sandbox', 't', sandbox)\nfn()  -- restricted environment" }
  ],
  keyTakeaway: "Sandbox untrusted code by restricting its environment to safe functions only.",
  references: [{ title: "Lua Sandbox", url: "http://lua-users.org/wiki/SandBoxes" }]
},
"lua.testing-security.are-file-paths-validated-to-prevent-directory-traversal": {
  whatItMeans: "File paths constructed from user input must be validated to prevent directory traversal attacks using `..` sequences.",
  whyItMatters: "An attacker can use `../../etc/passwd` style paths to read or write files outside the intended directory.",
  howToVerify: "- Check for user input in file path construction\n- Look for `..` path traversal prevention\n- Verify paths are canonicalized and checked against an allowed base directory",
  exampleComment: "This constructs a file path from user input without checking for `..` sequences. An attacker could access files outside the data directory.",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local function read_template(name)\n  local f = io.open('templates/' .. name)\n  -- name could be '../../etc/passwd'\n  return f:read('*a')\nend" },
    { label: "Good", language: "lua", code: "local function read_template(name)\n  if name:find('%.%.') or name:find('[/\\\\]') then\n    return nil, 'invalid template name'\n  end\n  local f = io.open('templates/' .. name)\n  if not f then return nil, 'not found' end\n  return f:read('*a')\nend" }
  ],
  keyTakeaway: "Validate file paths from user input. Block `..` and path separators.",
  references: []
},

// DOCUMENTATION (43-45)
"lua.documentation.are-ldoc-or-luadoc-comments-added-for-public-apis": {
  whatItMeans: "Public module functions should have LDoc or LuaDoc comments describing parameters, return values, and usage.",
  whyItMatters: "Documentation on public APIs reduces the time developers spend reading source code. It enables auto-generated docs and IDE tooltips.",
  howToVerify: "- Check new public functions for doc comments\n- Verify @param and @return tags are present\n- Look for missing documentation on module return tables",
  exampleComment: "This new public function `parse_config` has no documentation. Could you add LDoc comments with @param and @return?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "function M.parse(input, options)\n  -- no docs\nend" },
    { label: "Good", language: "lua", code: "--- Parse input string into a structured table.\n-- @param input string The raw input to parse\n-- @param options table Optional parsing options\n-- @return table The parsed result\n-- @return nil, string Error message on failure\nfunction M.parse(input, options)\nend" }
  ],
  keyTakeaway: "Document public APIs with LDoc comments so users do not have to read the implementation.",
  references: [{ title: "LDoc", url: "https://stevedonovan.github.io/ldoc/" }]
},
"lua.documentation.are-complex-algorithms-explained-in-comments": {
  whatItMeans: "Complex algorithms, non-obvious logic, and workarounds should have comments explaining the reasoning.",
  whyItMatters: "Code explains what happens. Comments explain why. Without comments on complex logic, future developers waste time reverse-engineering the intent.",
  howToVerify: "- Look for complex logic without explanatory comments\n- Check that workarounds reference the issue they work around\n- Verify algorithm comments explain the approach, not just restate the code",
  exampleComment: "This bit manipulation logic is not obvious. Could you add a comment explaining the algorithm and why this approach was chosen?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "local function hash(s)\n  local h = 5381\n  for i = 1, #s do\n    h = h * 33 + s:byte(i)\n  end\n  return h % 1000003\nend" },
    { label: "Good", language: "lua", code: "-- DJB2 hash function. Uses prime 33 multiplier\n-- and mod by a prime to distribute keys evenly.\nlocal function hash(s)\n  local h = 5381\n  for i = 1, #s do\n    h = h * 33 + s:byte(i)\n  end\n  return h % 1000003\nend" }
  ],
  keyTakeaway: "Comment the why, not the what. Complex logic deserves an explanation.",
  references: []
},
"lua.documentation.is-the-readme-updated-for-api-changes": {
  whatItMeans: "When public APIs change (new functions, changed signatures, removed features), the README or documentation must be updated.",
  whyItMatters: "Outdated documentation is worse than no documentation. Users following stale docs will hit errors and lose trust.",
  howToVerify: "- Check if the PR changes public APIs\n- Verify the README or docs reflect the changes\n- Look for updated usage examples",
  exampleComment: "This PR adds a new `parse_options` parameter but the README examples do not show it. Could you update the usage section?",
  codeExamples: [
    { label: "Bad", language: "lua", code: "-- README says: result = M.parse(input)\n-- But code now requires: result = M.parse(input, options)" },
    { label: "Good", language: "lua", code: "-- README updated:\n-- result = M.parse(input, { strict = true })\n-- See options table for all parameters" }
  ],
  keyTakeaway: "Update documentation when APIs change. Future users will thank you.",
  references: []
},

};
